# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
executors:
  machine:
    machine:
      image: ubuntu-2004:202008-01
    working_directory: ~/spring-sample
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
commands:
  restore_gradle_cache:
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
  save_gradle_cache:
    steps:
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
  docker_compose_up:
    steps:
      - run: docker-compose -f ./devtool/docker-compose.yml up -d
      - run: sleep 10

jobs:
  dependencies:
    executor:
      name: machine
    steps:
      - checkout
      - restore_gradle_cache
      - run: ./gradlew dependencies
      - save_gradle_cache

  check:
    executor:
      name: machine
    steps:
      - checkout
      - restore_gradle_cache
      - run: ./gradlew check -x test

  test:
    executor:
      name: machine
    steps:
      - checkout
      - docker_compose_up
      - restore_gradle_cache
      - run: ./gradlew check test jacocoTestReport coveralls

  build:
    executor:
      name: machine
    steps:
      - checkout
      - restore_gradle_cache
      - run: ./gradlew build -x test

workflows:
  version: 2.1
  test_and_build:
    jobs:
      - dependencies
      - check:
          requires:
            - dependencies
      - test:
          requires:
            - check
      - build:
          requires:
            - test
