# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
jobs:
  dependencies:
    machine:
      image: circleci/classic:edge
    working_directory: ~/spring-sample
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - circleci-install java openjdk11
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

  test:
    machine:
      image: circleci/classic:edge
    working_directory: ~/spring-sample
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - circleci-install java openjdk11
      - docker-compose -f ./devtool/docker-compose.yml up -d
      - run: gradle test

  build:
    machine:
      image: circleci/classic:edge
    working_directory: ~/spring-sample
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - circleci-install java openjdk11
      - run: gradle build

workflows:
  version: 2.1
  test_and_build:
    jobs:
      - dependencies
      - test
      - build
